export const EVENTS_CLEAR = 'EVENTS_CLEAR'
export const EVENT_CLEAR = 'EVENT_CLEAR'
export const EVENTS_FILTER = 'EVENTS_FILTER'

export const EVENTS_FORM_DATA = 'EVENTS_FORM_DATA'
export const EVENT_ADD = 'EVENT_ADD'
export const EVENTS_SORT = 'EVENTS_SORT'

export const EVENTS_GET_START = 'EVENTS_GET_START'
export const EVENTS_GET_SUCCESS = 'EVENTS_GET_SUCCESS'
export const EVENTS_GET_ERROR = 'EVENTS_GET_ERROR'
